package com.example.alarm_jinxuan.utils

import com.example.alarm_jinxuan.model.WorldClockEntity
import java.text.Collator
import java.util.Locale

object WorldClockUtils {
    // 城市数据结构：城市中文名、英文名、国家中文名、国家拼音、时区ID、时间偏移
    private data class CityData(
        val cityName: String,
        val cityEnglishName: String,
        val countryName: String,
        val countryPinyin: String,
        val zoneId: String,
        val timeOffset: String
    )

    private val HOT_CITIES = listOf(
        // 【亚洲：180个】
        // 中国（40个）
        CityData("北京", "Beijing", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("上海", "Shanghai", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("广州", "Guangzhou", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("深圳", "Shenzhen", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("重庆", "Chongqing", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("成都", "Chengdu", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("杭州", "Hangzhou", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("武汉", "Wuhan", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("南京", "Nanjing", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("西安", "Xi'an", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("天津", "Tianjin", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("苏州", "Suzhou", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("郑州", "Zhengzhou", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("长沙", "Changsha", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("青岛", "Qingdao", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("宁波", "Ningbo", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("沈阳", "Shenyang", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("合肥", "Hefei", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("厦门", "Xiamen", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("福州", "Fuzhou", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("无锡", "Wuxi", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("济南", "Jinan", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("大连", "Dalian", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("昆明", "Kunming", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("哈尔滨", "Harbin", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("长春", "Changchun", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("石家庄", "Shijiazhuang", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("南宁", "Nanning", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("泉州", "Quanzhou", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("温州", "Wenzhou", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("佛山", "Foshan", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("东莞", "Dongguan", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("唐山", "Tangshan", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("烟台", "Yantai", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("常州", "Changzhou", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("徐州", "Xuzhou", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("潍坊", "Weifang", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("绍兴", "Shaoxing", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("南通", "Nantong", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("嘉兴", "Jiaxing", "中国", "zhongguo", "Asia/Shanghai", "+08:00"),
        CityData("香港", "Hong Kong", "中国", "zhongguo", "Asia/Hong_Kong", "+08:00"),
        CityData("台北", "Taipei", "中国", "zhongguo", "Asia/Taipei", "+08:00"),
        CityData("高雄", "Kaohsiung", "中国", "zhongguo", "Asia/Taipei", "+08:00"),

        // 日本（10个）
        CityData("东京", "Tokyo", "日本", "riben", "Asia/Tokyo", "+09:00"),
        CityData("大阪", "Osaka", "日本", "riben", "Asia/Tokyo", "+09:00"),
        CityData("横滨", "Yokohama", "日本", "riben", "Asia/Tokyo", "+09:00"),
        CityData("名古屋", "Nagoya", "日本", "riben", "Asia/Tokyo", "+09:00"),
        CityData("神户", "Kobe", "日本", "riben", "Asia/Tokyo", "+09:00"),
        CityData("京都", "Kyoto", "日本", "riben", "Asia/Tokyo", "+09:00"),
        CityData("福冈", "Fukuoka", "日本", "riben", "Asia/Tokyo", "+09:00"),
        CityData("札幌", "Sapporo", "日本", "riben", "Asia/Tokyo", "+09:00"),
        CityData("广岛", "Hiroshima", "日本", "riben", "Asia/Tokyo", "+09:00"),
        CityData("仙台", "Sendai", "日本", "riben", "Asia/Tokyo", "+09:00"),

        // 韩国（5个）
        CityData("首尔", "Seoul", "韩国", "hanguo", "Asia/Seoul", "+09:00"),
        CityData("釜山", "Busan", "韩国", "hanguo", "Asia/Seoul", "+09:00"),
        CityData("仁川", "Incheon", "韩国", "hanguo", "Asia/Seoul", "+09:00"),
        CityData("大邱", "Daegu", "韩国", "hanguo", "Asia/Seoul", "+09:00"),
        CityData("大田", "Daejeon", "韩国", "hanguo", "Asia/Seoul", "+09:00"),

        // 东南亚（23个）
        CityData("新加坡", "Singapore", "东南亚", "dongnanya", "Asia/Singapore", "+08:00"),
        CityData("曼谷", "Bangkok", "东南亚", "dongnanya", "Asia/Bangkok", "+07:00"),
        CityData("清迈", "Chiang Mai", "东南亚", "dongnanya", "Asia/Bangkok", "+07:00"),
        CityData("普吉岛", "Phuket", "东南亚", "dongnanya", "Asia/Bangkok", "+07:00"),
        CityData("吉隆坡", "Kuala Lumpur", "东南亚", "dongnanya", "Asia/Kuala_Lumpur", "+08:00"),
        CityData("槟城", "Penang", "东南亚", "dongnanya", "Asia/Kuala_Lumpur", "+08:00"),
        CityData("新山", "Johor Bahru", "东南亚", "dongnanya", "Asia/Kuala_Lumpur", "+08:00"),
        CityData("雅加达", "Jakarta", "东南亚", "dongnanya", "Asia/Jakarta", "+07:00"),
        CityData("泗水", "Surabaya", "东南亚", "dongnanya", "Asia/Jakarta", "+07:00"),
        CityData("万隆", "Bandung", "东南亚", "dongnanya", "Asia/Jakarta", "+07:00"),
        CityData("巴厘岛", "Bali", "东南亚", "dongnanya", "Asia/Makassar", "+08:00"),
        CityData("马尼拉", "Manila", "东南亚", "dongnanya", "Asia/Manila", "+08:00"),
        CityData("宿务", "Cebu", "东南亚", "dongnanya", "Asia/Manila", "+08:00"),
        CityData("达沃", "Davao", "东南亚", "dongnanya", "Asia/Manila", "+08:00"),
        CityData("胡志明市", "Ho Chi Minh City", "东南亚", "dongnanya", "Asia/Ho_Chi_Minh", "+07:00"),
        CityData("金边", "Phnom Penh", "东南亚", "dongnanya", "Asia/Phnom_Penh", "+07:00"),
        CityData("暹粒", "Siem Reap", "东南亚", "dongnanya", "Asia/Phnom_Penh", "+07:00"),
        CityData("仰光", "Yangon", "东南亚", "dongnanya", "Asia/Yangon", "+06:30"),
        CityData("内比都", "Naypyidaw", "东南亚", "dongnanya", "Asia/Yangon", "+06:30"),
        CityData("加德满都", "Kathmandu", "东南亚", "dongnanya", "Asia/Kathmandu", "+05:45"),
        CityData("加尔各答", "Kolkata", "东南亚", "dongnanya", "Asia/Kolkata", "+05:30"),
        CityData("金奈", "Chennai", "东南亚", "dongnanya", "Asia/Kolkata", "+05:30"),
        CityData("海德拉巴", "Hyderabad", "东南亚", "dongnanya", "Asia/Kolkata", "+05:30"),

        // 南亚/西亚（25个）
        CityData("卡拉奇", "Karachi", "西亚", "xiya", "Asia/Karachi", "+05:00"),
        CityData("拉合尔", "Lahore", "西亚", "xiya", "Asia/Karachi", "+05:00"),
        CityData("伊斯兰堡", "Islamabad", "西亚", "xiya", "Asia/Karachi", "+05:00"),
        CityData("迪拜", "Dubai", "西亚", "xiya", "Asia/Dubai", "+04:00"),
        CityData("阿布扎比", "Abu Dhabi", "西亚", "xiya", "Asia/Dubai", "+04:00"),
        CityData("沙迦", "Sharjah", "西亚", "xiya", "Asia/Dubai", "+04:00"),
        CityData("利雅得", "Riyadh", "西亚", "xiya", "Asia/Riyadh", "+03:00"),
        CityData("吉达", "Jeddah", "西亚", "xiya", "Asia/Riyadh", "+03:00"),
        CityData("麦加", "Mecca", "西亚", "xiya", "Asia/Riyadh", "+03:00"),
        CityData("德黑兰", "Tehran", "西亚", "xiya", "Asia/Tehran", "+03:30"),
        CityData("伊斯法罕", "Isfahan", "西亚", "xiya", "Asia/Tehran", "+03:30"),
        CityData("巴格达", "Baghdad", "西亚", "xiya", "Asia/Baghdad", "+03:00"),
        CityData("巴士拉", "Basra", "西亚", "xiya", "Asia/Baghdad", "+03:00"),
        CityData("科威特城", "Kuwait City", "西亚", "xiya", "Asia/Kuwait", "+03:00"),
        CityData("麦纳麦", "Manama", "西亚", "xiya", "Asia/Bahrain", "+03:00"),
        CityData("多哈", "Doha", "西亚", "xiya", "Asia/Qatar", "+03:00"),
        CityData("安曼", "Amman", "西亚", "xiya", "Asia/Amman", "+03:00"),
        CityData("贝鲁特", "Beirut", "西亚", "xiya", "Asia/Beirut", "+02:00"),
        CityData("大马士革", "Damascus", "西亚", "xiya", "Asia/Damascus", "+02:00"),
        CityData("耶路撒冷", "Jerusalem", "西亚", "xiya", "Asia/Jerusalem", "+02:00"),
        CityData("特拉维夫", "Tel Aviv", "西亚", "xiya", "Asia/Jerusalem", "+02:00"),
        CityData("利马索尔", "Limassol", "西亚", "xiya", "Asia/Nicosia", "+02:00"),
        CityData("尼科西亚", "Nicosia", "西亚", "xiya", "Asia/Nicosia", "+02:00"),
        CityData("喀布尔", "Kabul", "西亚", "xiya", "Asia/Kabul", "+04:30"),
        CityData("坎大哈", "Kandahar", "西亚", "xiya", "Asia/Kabul", "+04:30"),

        // 中亚（10个）
        CityData("塔什干", "Tashkent", "中亚", "zhongya", "Asia/Tashkent", "+05:00"),
        CityData("努尔苏丹", "Nur-Sultan", "中亚", "zhongya", "Asia/Novosibirsk", "+07:00"),
        CityData("阿拉木图", "Almaty", "中亚", "zhongya", "Asia/Almaty", "+05:00"),
        CityData("比什凯克", "Bishkek", "中亚", "zhongya", "Asia/Bishkek", "+06:00"),
        CityData("杜尚别", "Dushanbe", "中亚", "zhongya", "Asia/Dushanbe", "+05:00"),
        CityData("苦盏", "Khujand", "中亚", "zhongya", "Asia/Dushanbe", "+05:00"),
        CityData("阿什哈巴德", "Ashgabat", "中亚", "zhongya", "Asia/Ashgabat", "+05:00"),
        CityData("马什哈德", "Mashhad", "西亚", "xiya", "Asia/Tehran", "+03:30"),
        CityData("伊斯坎德尔", "Iskandar", "中亚", "zhongya", "Asia/Tashkent", "+05:00"),
        CityData("撒马尔罕", "Samarkand", "中亚", "zhongya", "Asia/Tashkent", "+05:00"),

        // 西亚（20个）
        CityData("伊斯坦布尔", "Istanbul", "西亚", "xiya", "Europe/Istanbul", "+03:00"),
        CityData("安卡拉", "Ankara", "西亚", "xiya", "Europe/Istanbul", "+03:00"),
        CityData("伊兹密尔", "Izmir", "西亚", "xiya", "Europe/Istanbul", "+03:00"),
        CityData("布尔萨", "Bursa", "西亚", "xiya", "Europe/Istanbul", "+03:00"),
        CityData("安塔利亚", "Antalya", "西亚", "xiya", "Europe/Istanbul", "+03:00"),
        CityData("加济安泰普", "Gaziantep", "西亚", "xiya", "Europe/Istanbul", "+03:00"),
        CityData("贝伊奥卢", "Beyoglu", "西亚", "xiya", "Europe/Istanbul", "+03:00"),
        CityData("梅尔辛", "Mersin", "西亚", "xiya", "Europe/Istanbul", "+03:00"),
        CityData("阿达纳", "Adana", "西亚", "xiya", "Europe/Istanbul", "+03:00"),
        CityData("科尼亚", "Konya", "西亚", "xiya", "Europe/Istanbul", "+03:00"),
        CityData("吉布提市", "Djibouti City", "西亚", "xiya", "Africa/Djibouti", "+03:00"),
        CityData("亚丁", "Aden", "西亚", "xiya", "Asia/Aden", "+03:00"),
        CityData("萨那", "Sana'a", "西亚", "xiya", "Asia/Aden", "+03:00"),
        CityData("马斯喀特", "Muscat", "西亚", "xiya", "Asia/Muscat", "+04:00"),
        CityData("塞拉莱", "Salalah", "西亚", "xiya", "Asia/Muscat", "+04:00"),
        CityData("迪拜沙迦", "Sharjah", "西亚", "xiya", "Asia/Dubai", "+04:00"),
        CityData("富查伊拉", "Fujairah", "西亚", "xiya", "Asia/Dubai", "+04:00"),
        CityData("阿治曼", "Ajman", "西亚", "xiya", "Asia/Dubai", "+04:00"),
        CityData("乌姆盖万", "Umm Al Quwain", "西亚", "xiya", "Asia/Dubai", "+04:00"),
        CityData("哈伊马角", "Ras Al Khaimah", "西亚", "xiya", "Asia/Dubai", "+04:00"),

        // 【欧洲：150个】
        // 西欧（40个）
        CityData("伦敦", "London", "英国", "yingguo", "Europe/London", "+00:00"),
        CityData("伯明翰", "Birmingham", "英国", "yingguo", "Europe/London", "+00:00"),
        CityData("曼彻斯特", "Manchester", "英国", "yingguo", "Europe/London", "+00:00"),
        CityData("利物浦", "Liverpool", "英国", "yingguo", "Europe/London", "+00:00"),
        CityData("格拉斯哥", "Glasgow", "英国", "yingguo", "Europe/London", "+00:00"),
        CityData("爱丁堡", "Edinburgh", "英国", "yingguo", "Europe/London", "+00:00"),
        CityData("利兹", "Leeds", "英国", "yingguo", "Europe/London", "+00:00"),
        CityData("纽卡斯尔", "Newcastle", "英国", "yingguo", "Europe/London", "+00:00"),
        CityData("谢菲尔德", "Sheffield", "英国", "yingguo", "Europe/London", "+00:00"),
        CityData("布里斯托尔", "Bristol", "英国", "yingguo", "Europe/London", "+00:00"),
        CityData("巴黎", "Paris", "法国", "faguo", "Europe/Paris", "+01:00"),
        CityData("马赛", "Marseille", "法国", "faguo", "Europe/Paris", "+01:00"),
        CityData("里昂", "Lyon", "法国", "faguo", "Europe/Paris", "+01:00"),
        CityData("图卢兹", "Toulouse", "法国", "faguo", "Europe/Paris", "+01:00"),
        CityData("尼斯", "Nice", "法国", "faguo", "Europe/Paris", "+01:00"),
        CityData("南特", "Nantes", "法国", "faguo", "Europe/Paris", "+01:00"),
        CityData("斯特拉斯堡", "Strasbourg", "法国", "faguo", "Europe/Paris", "+01:00"),
        CityData("蒙彼利埃", "Montpellier", "法国", "faguo", "Europe/Paris", "+01:00"),
        CityData("波尔多", "Bordeaux", "法国", "faguo", "Europe/Paris", "+01:00"),
        CityData("里尔", "Lille", "法国", "faguo", "Europe/Paris", "+01:00"),
        CityData("柏林", "Berlin", "德国", "deguo", "Europe/Berlin", "+01:00"),
        CityData("慕尼黑", "Munich", "德国", "deguo", "Europe/Berlin", "+01:00"),
        CityData("汉堡", "Hamburg", "德国", "deguo", "Europe/Berlin", "+01:00"),
        CityData("法兰克福", "Frankfurt", "德国", "deguo", "Europe/Berlin", "+01:00"),
        CityData("科隆", "Cologne", "德国", "deguo", "Europe/Berlin", "+01:00"),
        CityData("杜塞尔多夫", "Düsseldorf", "德国", "deguo", "Europe/Berlin", "+01:00"),
        CityData("斯图加特", "Stuttgart", "德国", "deguo", "Europe/Berlin", "+01:00"),
        CityData("多特蒙德", "Dortmund", "德国", "deguo", "Europe/Berlin", "+01:00"),
        CityData("埃森", "Essen", "德国", "deguo", "Europe/Berlin", "+01:00"),
        CityData("不来梅", "Bremen", "德国", "deguo", "Europe/Berlin", "+01:00"),
        CityData("阿姆斯特丹", "Amsterdam", "荷兰", "helan", "Europe/Amsterdam", "+01:00"),
        CityData("鹿特丹", "Rotterdam", "荷兰", "helan", "Europe/Amsterdam", "+01:00"),
        CityData("海牙", "The Hague", "荷兰", "helan", "Europe/Amsterdam", "+01:00"),
        CityData("乌得勒支", "Utrecht", "荷兰", "helan", "Europe/Amsterdam", "+01:00"),
        CityData("埃因霍温", "Eindhoven", "荷兰", "helan", "Europe/Amsterdam", "+01:00"),
        CityData("布鲁塞尔", "Brussels", "比利时", "bilishi", "Europe/Brussels", "+01:00"),
        CityData("安特卫普", "Antwerp", "比利时", "bilishi", "Europe/Brussels", "+01:00"),
        CityData("根特", "Ghent", "比利时", "bilishi", "Europe/Brussels", "+01:00"),
        CityData("沙勒罗瓦", "Charleroi", "比利时", "bilishi", "Europe/Brussels", "+01:00"),
        CityData("列日", "Liège", "比利时", "bilishi", "Europe/Brussels", "+01:00"),

        // 南欧（40个）
        CityData("罗马", "Rome", "意大利", "yidali", "Europe/Rome", "+01:00"),
        CityData("米兰", "Milan", "意大利", "yidali", "Europe/Rome", "+01:00"),
        CityData("那不勒斯", "Naples", "意大利", "yidali", "Europe/Rome", "+01:00"),
        CityData("都灵", "Turin", "意大利", "yidali", "Europe/Rome", "+01:00"),
        CityData("巴勒莫", "Palermo", "意大利", "yidali", "Europe/Rome", "+01:00"),
        CityData("热那亚", "Genoa", "意大利", "yidali", "Europe/Rome", "+01:00"),
        CityData("博洛尼亚", "Bologna", "意大利", "yidali", "Europe/Rome", "+01:00"),
        CityData("佛罗伦萨", "Florence", "意大利", "yidali", "Europe/Rome", "+01:00"),
        CityData("威尼斯", "Venice", "意大利", "yidali", "Europe/Rome", "+01:00"),
        CityData("比萨", "Pisa", "意大利", "yidali", "Europe/Rome", "+01:00"),
        CityData("马德里", "Madrid", "西班牙", "xibanya", "Europe/Madrid", "+01:00"),
        CityData("巴塞罗那", "Barcelona", "西班牙", "xibanya", "Europe/Madrid", "+01:00"),
        CityData("瓦伦西亚", "Valencia", "西班牙", "xibanya", "Europe/Madrid", "+01:00"),
        CityData("塞维利亚", "Seville", "西班牙", "xibanya", "Europe/Madrid", "+01:00"),
        CityData("马拉加", "Malaga", "西班牙", "xibanya", "Europe/Madrid", "+01:00"),
        CityData("毕尔巴鄂", "Bilbao", "西班牙", "xibanya", "Europe/Madrid", "+01:00"),
        CityData("萨拉戈萨", "Zaragoza", "西班牙", "xibanya", "Europe/Madrid", "+01:00"),
        CityData("穆尔西亚", "Murcia", "西班牙", "xibanya", "Europe/Madrid", "+01:00"),
        CityData("帕尔马", "Palma", "西班牙", "xibanya", "Europe/Madrid", "+01:00"),
        CityData("格拉纳达", "Granada", "西班牙", "xibanya", "Europe/Madrid", "+01:00"),
        CityData("里斯本", "Lisbon", "葡萄牙", "putaoya", "Europe/Lisbon", "+00:00"),
        CityData("波尔图", "Porto", "葡萄牙", "putaoya", "Europe/Lisbon", "+00:00"),
        CityData("布拉加", "Braga", "葡萄牙", "putaoya", "Europe/Lisbon", "+00:00"),
        CityData("科英布拉", "Coimbra", "葡萄牙", "putaoya", "Europe/Lisbon", "+00:00"),
        CityData("法鲁", "Faro", "葡萄牙", "putaoya", "Europe/Lisbon", "+00:00"),
        CityData("雅典", "Athens", "希腊", "xila", "Europe/Athens", "+02:00"),
        CityData("塞萨洛尼基", "Thessaloniki", "希腊", "xila", "Europe/Athens", "+02:00"),
        CityData("帕特雷", "Patras", "希腊", "xila", "Europe/Athens", "+02:00"),
        CityData("伊拉克利翁", "Heraklion", "希腊", "xila", "Europe/Athens", "+02:00"),
        CityData("拉里萨", "Larissa", "希腊", "xila", "Europe/Athens", "+02:00"),
        CityData("布加勒斯特", "Bucharest", "罗马尼亚", "luomaniya", "Europe/Bucharest", "+02:00"),
        CityData("雅西", "Iasi", "罗马尼亚", "luomaniya", "Europe/Bucharest", "+02:00"),
        CityData("克卢日-纳波卡", "Cluj-Napoca", "罗马尼亚", "luomaniya", "Europe/Bucharest", "+02:00"),
        CityData("蒂米什瓦拉", "Timisoara", "罗马尼亚", "luomaniya", "Europe/Bucharest", "+02:00"),
        CityData("康斯坦察", "Constanta", "罗马尼亚", "luomaniya", "Europe/Bucharest", "+02:00"),
        CityData("索非亚", "Sofia", "保加利亚", "baojialiya", "Europe/Sofia", "+02:00"),
        CityData("普罗夫迪夫", "Plovdiv", "保加利亚", "baojialiya", "Europe/Sofia", "+02:00"),
        CityData("瓦尔纳", "Varna", "保加利亚", "baojialiya", "Europe/Sofia", "+02:00"),
        CityData("布尔加斯", "Burgas", "保加利亚", "baojialiya", "Europe/Sofia", "+02:00"),
        CityData("斯科普里", "Skopje", "北马其顿", "beimaqidun", "Europe/Skopje", "+02:00"),

        // 中欧/东欧（40个）
        CityData("维也纳", "Vienna", "奥地利", "aodili", "Europe/Vienna", "+01:00"),
        CityData("格拉茨", "Graz", "奥地利", "aodili", "Europe/Vienna", "+01:00"),
        CityData("林茨", "Linz", "奥地利", "aodili", "Europe/Vienna", "+01:00"),
        CityData("萨尔茨堡", "Salzburg", "奥地利", "aodili", "Europe/Vienna", "+01:00"),
        CityData("因斯布鲁克", "Innsbruck", "奥地利", "aodili", "Europe/Vienna", "+01:00"),
        CityData("布拉格", "Prague", "捷克", "jieke", "Europe/Prague", "+01:00"),
        CityData("布尔诺", "Brno", "捷克", "jieke", "Europe/Prague", "+01:00"),
        CityData("奥洛穆茨", "Olomouc", "捷克", "jieke", "Europe/Prague", "+01:00"),
        CityData("比尔森", "Plzen", "捷克", "jieke", "Europe/Prague", "+01:00"),
        CityData("利贝雷茨", "Liberec", "捷克", "jieke", "Europe/Prague", "+01:00"),
        CityData("华沙", "Warsaw", "波兰", "bolan", "Europe/Warsaw", "+01:00"),
        CityData("克拉科夫", "Krakow", "波兰", "bolan", "Europe/Warsaw", "+01:00"),
        CityData("罗兹", "Lodz", "波兰", "bolan", "Europe/Warsaw", "+01:00"),
        CityData("弗罗茨瓦夫", "Wroclaw", "波兰", "bolan", "Europe/Warsaw", "+01:00"),
        CityData("波兹南", "Poznan", "波兰", "bolan", "Europe/Warsaw", "+01:00"),
        CityData("格但斯克", "Gdansk", "波兰", "bolan", "Europe/Warsaw", "+01:00"),
        CityData("基辅", "Kyiv", "乌克兰", "wukelan", "Europe/Kyiv", "+02:00"),
        CityData("哈尔科夫", "Kharkiv", "乌克兰", "wukelan", "Europe/Kyiv", "+02:00"),
        CityData("敖德萨", "Odesa", "乌克兰", "wukelan", "Europe/Kyiv", "+02:00"),
        CityData("第聂伯罗", "Dnipro", "乌克兰", "wukelan", "Europe/Kyiv", "+02:00"),
        CityData("顿涅茨克", "Donetsk", "乌克兰", "wukelan", "Europe/Kyiv", "+02:00"),
        CityData("明斯克", "Minsk", "白俄罗斯", "baieluosi", "Europe/Minsk", "+03:00"),
        CityData("戈梅利", "Gomel", "白俄罗斯", "baieluosi", "Europe/Minsk", "+03:00"),
        CityData("莫吉廖夫", "Mogilev", "白俄罗斯", "baieluosi", "Europe/Minsk", "+03:00"),
        CityData("维捷布斯克", "Vitebsk", "白俄罗斯", "baieluosi", "Europe/Minsk", "+03:00"),
        CityData("布列斯特", "Brest", "白俄罗斯", "baieluosi", "Europe/Minsk", "+03:00"),
        CityData("莫斯科", "Moscow", "俄罗斯", "eluosi", "Europe/Moscow", "+03:00"),
        CityData("圣彼得堡", "Saint Petersburg", "俄罗斯", "eluosi", "Europe/Moscow", "+03:00"),
        CityData("新西伯利亚", "Novosibirsk", "俄罗斯", "eluosi", "Asia/Novosibirsk", "+07:00"),
        CityData("叶卡捷琳堡", "Yekaterinburg", "俄罗斯", "eluosi", "Asia/Yekaterinburg", "+05:00"),
        CityData("下诺夫哥罗德", "Nizhny Novgorod", "俄罗斯", "eluosi", "Europe/Moscow", "+03:00"),
        CityData("喀山", "Kazan", "俄罗斯", "eluosi", "Europe/Moscow", "+03:00"),
        CityData("萨马拉", "Samara", "俄罗斯", "eluosi", "Europe/Samara", "+04:00"),
        CityData("车里雅宾斯克", "Chelyabinsk", "俄罗斯", "eluosi", "Asia/Yekaterinburg", "+05:00"),
        CityData("鄂木斯克", "Omsk", "俄罗斯", "eluosi", "Asia/Omsk", "+06:00"),
        CityData("彼尔姆", "Perm", "俄罗斯", "eluosi", "Asia/Yekaterinburg", "+05:00"),
        CityData("沃罗涅日", "Voronezh", "俄罗斯", "eluosi", "Europe/Moscow", "+03:00"),
        CityData("伏尔加格勒", "Volgograd", "俄罗斯", "eluosi", "Europe/Moscow", "+03:00"),

        // 北欧（30个）
        CityData("斯德哥尔摩", "Stockholm", "瑞典", "ruidian", "Europe/Stockholm", "+01:00"),
        CityData("哥德堡", "Gothenburg", "瑞典", "ruidian", "Europe/Stockholm", "+01:00"),
        CityData("马尔默", "Malmö", "瑞典", "ruidian", "Europe/Stockholm", "+01:00"),
        CityData("乌普萨拉", "Uppsala", "瑞典", "ruidian", "Europe/Stockholm", "+01:00"),
        CityData("林雪平", "Linköping", "瑞典", "ruidian", "Europe/Stockholm", "+01:00"),
        CityData("奥斯陆", "Oslo", "挪威", "nuowei", "Europe/Oslo", "+01:00"),
        CityData("卑尔根", "Bergen", "挪威", "nuowei", "Europe/Oslo", "+01:00"),
        CityData("特隆赫姆", "Trondheim", "挪威", "nuowei", "Europe/Oslo", "+01:00"),
        CityData("斯塔万格", "Stavanger", "挪威", "nuowei", "Europe/Oslo", "+01:00"),
        CityData("克里斯蒂安桑", "Kristiansand", "挪威", "nuowei", "Europe/Oslo", "+01:00"),
        CityData("哥本哈根", "Copenhagen", "丹麦", "danmai", "Europe/Copenhagen", "+01:00"),
        CityData("奥胡斯", "Aarhus", "丹麦", "danmai", "Europe/Copenhagen", "+01:00"),
        CityData("欧登塞", "Odense", "丹麦", "danmai", "Europe/Copenhagen", "+01:00"),
        CityData("奥尔堡", "Aalborg", "丹麦", "danmai", "Europe/Copenhagen", "+01:00"),
        CityData("埃斯比约", "Esbjerg", "丹麦", "danmai", "Europe/Copenhagen", "+01:00"),
        CityData("赫尔辛基", "Helsinki", "芬兰", "fenlan", "Europe/Helsinki", "+02:00"),
        CityData("坦佩雷", "Tampere", "芬兰", "fenlan", "Europe/Helsinki", "+02:00"),
        CityData("图尔库", "Turku", "芬兰", "fenlan", "Europe/Helsinki", "+02:00"),
        CityData("奥卢", "Oulu", "芬兰", "fenlan", "Europe/Helsinki", "+02:00"),
        CityData("拉赫蒂", "Lahti", "芬兰", "fenlan", "Europe/Helsinki", "+02:00"),
        CityData("雷克雅未克", "Reykjavik", "冰岛", "bingdao", "Atlantic/Reykjavik", "+00:00"),
        CityData("阿克雷里", "Akureyri", "冰岛", "bingdao", "Atlantic/Reykjavik", "+00:00"),
        CityData("伊萨菲厄泽", "Ísafjörður", "冰岛", "bingdao", "Atlantic/Reykjavik", "+00:00"),
        CityData("博尔加内斯", "Borgarnes", "冰岛", "bingdao", "Atlantic/Reykjavik", "+00:00"),
        CityData("哈布纳菲厄泽", "Hafnarfjörður", "冰岛", "bingdao", "Atlantic/Reykjavik", "+00:00"),
        CityData("塔林", "Tallinn", "波罗的海三国", "boluohaisanguo", "Europe/Tallinn", "+02:00"),
        CityData("里加", "Riga", "波罗的海三国", "boluohaisanguo", "Europe/Riga", "+02:00"),
        CityData("维尔纽斯", "Vilnius", "波罗的海三国", "boluohaisanguo", "Europe/Vilnius", "+02:00"),
        CityData("塔尔图", "Tartu", "波罗的海三国", "boluohaisanguo", "Europe/Tallinn", "+02:00"),
        CityData("道加瓦皮尔斯", "Daugavpils", "波罗的海三国", "boluohaisanguo", "Europe/Riga", "+02:00"),

        // 【美洲：120个】
        // 北美（60个）
        CityData("纽约", "New York", "美国", "meiguo", "America/New_York", "-04:00"),
        CityData("洛杉矶", "Los Angeles", "美国", "meiguo", "America/Los_Angeles", "-07:00"),
        CityData("芝加哥", "Chicago", "美国", "meiguo", "America/Chicago", "-05:00"),
        CityData("休斯顿", "Houston", "美国", "meiguo", "America/Chicago", "-05:00"),
        CityData("费城", "Philadelphia", "美国", "meiguo", "America/New_York", "-04:00"),
        CityData("菲尼克斯", "Phoenix", "美国", "meiguo", "America/Phoenix", "-07:00"),
        CityData("圣安东尼奥", "San Antonio", "美国", "meiguo", "America/Chicago", "-05:00"),
        CityData("圣地亚哥", "San Diego", "美国", "meiguo", "America/Los_Angeles", "-07:00"),
        CityData("达拉斯", "Dallas", "美国", "meiguo", "America/Chicago", "-05:00"),
        CityData("圣何塞", "San Jose", "美国", "meiguo", "America/Los_Angeles", "-07:00"),
        CityData("奥斯汀", "Austin", "美国", "meiguo", "America/Chicago", "-05:00"),
        CityData("杰克逊维尔", "Jacksonville", "美国", "meiguo", "America/New_York", "-04:00"),
        CityData("旧金山", "San Francisco", "美国", "meiguo", "America/Los_Angeles", "-07:00"),
        CityData("哥伦布", "Columbus", "美国", "meiguo", "America/New_York", "-04:00"),
        CityData("印第安纳波利斯", "Indianapolis", "美国", "meiguo", "America/Indiana/Indianapolis", "-04:00"),
        CityData("夏洛特", "Charlotte", "美国", "meiguo", "America/New_York", "-04:00"),
        CityData("西雅图", "Seattle", "美国", "meiguo", "America/Los_Angeles", "-07:00"),
        CityData("丹佛", "Denver", "美国", "meiguo", "America/Denver", "-06:00"),
        CityData("华盛顿", "Washington D.C.", "美国", "meiguo", "America/New_York", "-04:00"),
        CityData("波士顿", "Boston", "美国", "meiguo", "America/New_York", "-04:00"),
        CityData("迈阿密", "Miami", "美国", "meiguo", "America/New_York", "-04:00"),
        CityData("亚特兰大", "Atlanta", "美国", "meiguo", "America/New_York", "-04:00"),
        CityData("底特律", "Detroit", "美国", "meiguo", "America/New_York", "-04:00"),
        CityData("明尼阿波利斯", "Minneapolis", "美国", "meiguo", "America/Chicago", "-05:00"),
        CityData("巴尔的摩", "Baltimore", "美国", "meiguo", "America/New_York", "-04:00"),
        CityData("波特兰", "Portland", "美国", "meiguo", "America/Los_Angeles", "-07:00"),
        CityData("拉斯维加斯", "Las Vegas", "美国", "meiguo", "America/Los_Angeles", "-07:00"),
        CityData("克利夫兰", "Cleveland", "美国", "meiguo", "America/New_York", "-04:00"),
        CityData("辛辛那提", "Cincinnati", "美国", "meiguo", "America/New_York", "-04:00"),
        CityData("多伦多", "Toronto", "加拿大", "jianada", "America/Toronto", "-04:00"),
        CityData("蒙特利尔", "Montreal", "加拿大", "jianada", "America/Montreal", "-04:00"),
        CityData("温哥华", "Vancouver", "加拿大", "jianada", "America/Vancouver", "-07:00"),
        CityData("渥太华", "Ottawa", "加拿大", "jianada", "America/Toronto", "-04:00"),
        CityData("卡尔加里", "Calgary", "加拿大", "jianada", "America/Edmonton", "-06:00"),
        CityData("埃德蒙顿", "Edmonton", "加拿大", "jianada", "America/Edmonton", "-06:00"),
        CityData("魁北克市", "Quebec City", "加拿大", "jianada", "America/Montreal", "-04:00"),
        CityData("温尼伯", "Winnipeg", "加拿大", "jianada", "America/Winnipeg", "-05:00"),
        CityData("汉密尔顿", "Hamilton", "加拿大", "jianada", "America/Toronto", "-04:00"),
        CityData("哈利法克斯", "Halifax", "加拿大", "jianada", "America/Halifax", "-03:00"),
        CityData("里贾纳", "Regina", "加拿大", "jianada", "America/Regina", "-06:00"),
        CityData("萨斯卡通", "Saskatoon", "加拿大", "jianada", "America/Regina", "-06:00"),
        CityData("圣约翰斯", "St. John's", "加拿大", "jianada", "America/St_Johns", "-02:30"),
        CityData("维多利亚", "Victoria", "加拿大", "jianada", "America/Vancouver", "-07:00"),
        CityData("基奇纳", "Kitchener", "加拿大", "jianada", "America/Toronto", "-04:00"),
        CityData("伦敦（加）", "London (Canada)", "加拿大", "jianada", "America/Toronto", "-04:00"),
        CityData("温莎", "Windsor", "加拿大", "jianada", "America/Toronto", "-04:00"),
        CityData("奥沙瓦", "Oshawa", "加拿大", "jianada", "America/Toronto", "-04:00"),
        CityData("巴里", "Barrie", "加拿大", "jianada", "America/Toronto", "-04:00"),
        CityData("金斯敦", "Kingston", "加拿大", "jianada", "America/Toronto", "-04:00"),
        CityData("圭尔夫", "Guelph", "加拿大", "jianada", "America/Toronto", "-04:00"),
        CityData("萨德伯里", "Sudbury", "加拿大", "jianada", "America/Toronto", "-04:00"),
        CityData("桑德贝", "Thunder Bay", "加拿大", "jianada", "America/Winnipeg", "-05:00"),
        CityData("夏洛特敦", "Charlottetown", "加拿大", "jianada", "America/Halifax", "-03:00"),
        CityData("弗雷德里克顿", "Fredericton", "加拿大", "jianada", "America/Halifax", "-03:00"),
        CityData("蒙克顿", "Moncton", "加拿大", "jianada", "America/Halifax", "-03:00"),
        CityData("密西沙加", "Mississauga", "加拿大", "jianada", "America/Toronto", "-04:00"),

        // 南美（40个）
        CityData("圣保罗", "São Paulo", "巴西", "baxi", "America/Sao_Paulo", "-03:00"),
        CityData("里约热内卢", "Rio de Janeiro", "巴西", "baxi", "America/Sao_Paulo", "-03:00"),
        CityData("巴西利亚", "Brasilia", "巴西", "baxi", "America/Sao_Paulo", "-03:00"),
        CityData("贝洛奥里藏特", "Belo Horizonte", "巴西", "baxi", "America/Sao_Paulo", "-03:00"),
        CityData("萨尔瓦多", "Salvador", "巴西", "baxi", "America/Bahia", "-03:00"),
        CityData("福塔莱萨", "Fortaleza", "巴西", "baxi", "America/Fortaleza", "-03:00"),
        CityData("库里蒂巴", "Curitiba", "巴西", "baxi", "America/Sao_Paulo", "-03:00"),
        CityData("累西腓", "Recife", "巴西", "baxi", "America/Recife", "-03:00"),
        CityData("马瑙斯", "Manaus", "巴西", "baxi", "America/Manaus", "-04:00"),
        CityData("阿雷格里港", "Porto Alegre", "巴西", "baxi", "America/Sao_Paulo", "-03:00"),
        CityData("布宜诺斯艾利斯", "Buenos Aires", "阿根廷", "agenting", "America/Argentina/Buenos_Aires", "-03:00"),
        CityData("科尔多瓦", "Cordoba", "阿根廷", "agenting", "America/Argentina/Cordoba", "-03:00"),
        CityData("罗萨里奥", "Rosario", "阿根廷", "agenting", "America/Argentina/Buenos_Aires", "-03:00"),
        CityData("门多萨", "Mendoza", "阿根廷", "agenting", "America/Argentina/Mendoza", "-03:00"),
        CityData("图库曼", "Tucuman", "阿根廷", "agenting", "America/Argentina/Tucuman", "-03:00"),
        CityData("利马", "Lima", "秘鲁", "bilu", "America/Lima", "-05:00"),
        CityData("库斯科", "Cusco", "秘鲁", "bilu", "America/Lima", "-05:00"),
        CityData("阿雷基帕", "Arequipa", "秘鲁", "bilu", "America/Lima", "-05:00"),
        CityData("特鲁希略", "Trujillo", "秘鲁", "bilu", "America/Lima", "-05:00"),
        CityData("奇克拉约", "Chiclayo", "秘鲁", "bilu", "America/Lima", "-05:00"),
        CityData("圣地亚哥", "Santiago", "智利", "zhili", "America/Santiago", "-03:00"),
        CityData("瓦尔帕莱索", "Valparaiso", "智利", "zhili", "America/Santiago", "-03:00"),
        CityData("康塞普西翁", "Concepcion", "智利", "zhili", "America/Santiago", "-03:00"),
        CityData("拉塞雷纳", "La Serena", "智利", "zhili", "America/Santiago", "-03:00"),
        CityData("安托法加斯塔", "Antofagasta", "智利", "zhili", "America/Santiago", "-03:00"),
        CityData("波哥大", "Bogota", "哥伦比亚", "gelunbiya", "America/Bogota", "-05:00"),
        CityData("麦德林", "Medellin", "哥伦比亚", "gelunbiya", "America/Bogota", "-05:00"),
        CityData("卡利", "Cali", "哥伦比亚", "gelunbiya", "America/Bogota", "-05:00"),
        CityData("巴兰基亚", "Barranquilla", "哥伦比亚", "gelunbiya", "America/Bogota", "-05:00"),
        CityData("卡塔赫纳", "Cartagena", "哥伦比亚", "gelunbiya", "America/Bogota", "-05:00"),
        CityData("加拉加斯", "Caracas", "委内瑞拉", "weiruila", "America/Caracas", "-04:00"),
        CityData("马拉开波", "Maracaibo", "委内瑞拉", "weiruila", "America/Caracas", "-04:00"),
        CityData("巴伦西亚", "Valencia", "委内瑞拉", "weiruila", "America/Caracas", "-04:00"),
        CityData("基多", "Quito", "厄瓜多尔", "eguaduoer", "America/Guayaquil", "-05:00"),
        CityData("瓜亚基尔", "Guayaquil", "厄瓜多尔", "eguaduoer", "America/Guayaquil", "-05:00"),
        CityData("昆卡", "Cuenca", "厄瓜多尔", "eguaduoer", "America/Guayaquil", "-05:00"),
        CityData("拉巴斯", "La Paz", "玻利维亚", "boliweiya", "America/La_Paz", "-04:00"),
        CityData("苏克雷", "Sucre", "玻利维亚", "boliweiya", "America/La_Paz", "-04:00"),
        CityData("圣克鲁斯", "Santa Cruz", "玻利维亚", "boliweiya", "America/La_Paz", "-04:00"),

        // 中美/加勒比（20个）
        CityData("墨西哥城", "Mexico City", "墨西哥", "moxige", "America/Mexico_City", "-05:00"),
        CityData("瓜达拉哈拉", "Guadalajara", "墨西哥", "moxige", "America/Mexico_City", "-05:00"),
        CityData("蒙特雷", "Monterrey", "墨西哥", "moxige", "America/Mexico_City", "-05:00"),
        CityData("普埃布拉", "Puebla", "墨西哥", "moxige", "America/Mexico_City", "-05:00"),
        CityData("蒂华纳", "Tijuana", "墨西哥", "moxige", "America/Tijuana", "-07:00"),
        CityData("巴拿马城", "Panama City", "中美洲", "zhongmeizhou", "America/Panama", "-05:00"),
        CityData("圣何塞（哥）", "San Jose (Costa Rica)", "中美洲", "zhongmeizhou", "America/Costa_Rica", "-06:00"),
        CityData("危地马拉城", "Guatemala City", "中美洲", "zhongmeizhou", "America/Guatemala", "-06:00"),
        CityData("特古西加尔巴", "Tegucigalpa", "中美洲", "zhongmeizhou", "America/Tegucigalpa", "-06:00"),
        CityData("马那瓜", "Managua", "中美洲", "zhongmeizhou", "America/Managua", "-06:00"),
        CityData("圣萨尔瓦多", "San Salvador", "中美洲", "zhongmeizhou", "America/El_Salvador", "-06:00"),
        CityData("太子港", "Port-au-Prince", "加勒比地区", "jialebidiqu", "America/Port-au-Prince", "-04:00"),
        CityData("金斯敦", "Kingston", "加勒比地区", "jialebidiqu", "America/Jamaica", "-05:00"),
        CityData("哈瓦那", "Havana", "加勒比地区", "jialebidiqu", "America/Havana", "-04:00"),
        CityData("圣地亚哥（古）", "Santiago (Cuba)", "加勒比地区", "jialebidiqu", "America/Havana", "-04:00"),
        CityData("圣多明各", "Santo Domingo", "加勒比地区", "jialebidiqu", "America/Santo_Domingo", "-04:00"),
        CityData("拿骚", "Nassau", "加勒比地区", "jialebidiqu", "America/Nassau", "-04:00"),
        CityData("乔治敦", "Georgetown", "加勒比地区", "jialebidiqu", "America/Guyana", "-04:00"),
        CityData("西班牙港", "Port of Spain", "加勒比地区", "jialebidiqu", "America/Port_of_Spain", "-04:00"),
        CityData("金斯敦（牙）", "Kingston (Jamaica)", "加勒比地区", "jialebidiqu", "America/Jamaica", "-05:00"),

        // 【非洲：30个】
        CityData("开罗", "Cairo", "埃及", "aiji", "Africa/Cairo", "+02:00"),
        CityData("亚历山大", "Alexandria", "埃及", "aiji", "Africa/Cairo", "+02:00"),
        CityData("吉萨", "Giza", "埃及", "aiji", "Africa/Cairo", "+02:00"),
        CityData("卢克索", "Luxor", "埃及", "aiji", "Africa/Cairo", "+02:00"),
        CityData("阿斯旺", "Aswan", "埃及", "aiji", "Africa/Cairo", "+02:00"),
        CityData("约翰内斯堡", "Johannesburg", "南非", "nanfei", "Africa/Johannesburg", "+02:00"),
        CityData("开普敦", "Cape Town", "南非", "nanfei", "Africa/Johannesburg", "+02:00"),
        CityData("德班", "Durban", "南非", "nanfei", "Africa/Johannesburg", "+02:00"),
        CityData("比勒陀利亚", "Pretoria", "南非", "nanfei", "Africa/Johannesburg", "+02:00"),
        CityData("伊丽莎白港", "Port Elizabeth", "南非", "nanfei", "Africa/Johannesburg", "+02:00"),
        CityData("拉各斯", "Lagos", "尼日利亚", "niriliya", "Africa/Lagos", "+01:00"),
        CityData("卡诺", "Kano", "尼日利亚", "niriliya", "Africa/Lagos", "+01:00"),
        CityData("伊巴丹", "Ibadan", "尼日利亚", "niriliya", "Africa/Lagos", "+01:00"),
        CityData("阿布贾", "Abuja", "尼日利亚", "niriliya", "Africa/Lagos", "+01:00"),
        CityData("坎帕拉", "Kampala", "乌干达", "wuganda", "Africa/Kampala", "+03:00"),
        CityData("内罗毕", "Nairobi", "肯尼亚", "kenniya", "Africa/Nairobi", "+03:00"),
        CityData("蒙巴萨", "Mombasa", "肯尼亚", "kenniya", "Africa/Nairobi", "+03:00"),
        CityData("达累斯萨拉姆", "Dar es Salaam", "坦桑尼亚", "tansangniya", "Africa/Dar_es_Salaam", "+03:00"),
        CityData("坦噶", "Tanga", "坦桑尼亚", "tansangniya", "Africa/Dar_es_Salaam", "+03:00"),
        CityData("阿尔及尔", "Algiers", "阿尔及利亚", "aerjiya", "Africa/Algiers", "+01:00"),
        CityData("奥兰", "Oran", "阿尔及利亚", "aerjiya", "Africa/Algiers", "+01:00"),
        CityData("君士坦丁", "Constantine", "阿尔及利亚", "aerjiya", "Africa/Algiers", "+01:00"),
        CityData("卡萨布兰卡", "Casablanca", "摩洛哥", "moluoge", "Africa/Casablanca", "+00:00"),
        CityData("拉巴特", "Rabat", "摩洛哥", "moluoge", "Africa/Casablanca", "+00:00"),
        CityData("马拉喀什", "Marrakech", "摩洛哥", "moluoge", "Africa/Casablanca", "+00:00"),
        CityData("突尼斯市", "Tunis", "突尼斯", "tunisi", "Africa/Tunis", "+01:00"),
        CityData("苏塞", "Sousse", "突尼斯", "tunisi", "Africa/Tunis", "+01:00"),
        CityData("斯法克斯", "Sfax", "突尼斯", "tunisi", "Africa/Tunis", "+01:00"),
        CityData("阿克拉", "Accra", "加纳", "jiana", "Africa/Accra", "+00:00"),
        CityData("库马西", "Kumasi", "加纳", "jiana", "Africa/Accra", "+00:00"),

        // 【大洋洲：20个】
        CityData("悉尼", "Sydney", "澳大利亚", "aodaliya", "Australia/Sydney", "+11:00"),
        CityData("墨尔本", "Melbourne", "澳大利亚", "aodaliya", "Australia/Melbourne", "+11:00"),
        CityData("布里斯班", "Brisbane", "澳大利亚", "aodaliya", "Australia/Brisbane", "+10:00"),
        CityData("珀斯", "Perth", "澳大利亚", "aodaliya", "Australia/Perth", "+08:00"),
        CityData("阿德莱德", "Adelaide", "澳大利亚", "aodaliya", "Australia/Adelaide", "+10:30"),
        CityData("黄金海岸", "Gold Coast", "澳大利亚", "aodaliya", "Australia/Brisbane", "+10:00"),
        CityData("纽卡斯尔", "Newcastle", "澳大利亚", "aodaliya", "Australia/Sydney", "+11:00"),
        CityData("堪培拉", "Canberra", "澳大利亚", "aodaliya", "Australia/Canberra", "+11:00"),
        CityData("霍巴特", "Hobart", "澳大利亚", "aodaliya", "Australia/Hobart", "+11:00"),
        CityData("达尔文", "Darwin", "澳大利亚", "aodaliya", "Australia/Darwin", "+09:30"),
        CityData("奥克兰", "Auckland", "新西兰", "xinxilan", "Pacific/Auckland", "+13:00"),
        CityData("惠灵顿", "Wellington", "新西兰", "xinxilan", "Pacific/Auckland", "+13:00"),
        CityData("基督城", "Christchurch", "新西兰", "xinxilan", "Pacific/Auckland", "+13:00"),
        CityData("克赖斯特彻奇", "Christchurch", "新西兰", "xinxilan", "Pacific/Auckland", "+13:00"),
        CityData("达尼丁", "Dunedin", "新西兰", "xinxilan", "Pacific/Auckland", "+13:00"),
        CityData("斐济苏瓦", "Suva (Fiji)", "太平洋岛国", "taipingyangdaoguo", "Pacific/Fiji", "+12:00"),
        CityData("巴布亚新几内亚莫尔兹比港", "Port Moresby (PNG)", "太平洋岛国", "taipingyangdaoguo", "Pacific/Port_Moresby", "+10:00"),
        CityData("所罗门群岛霍尼亚拉", "Honiara (Solomon Islands)", "太平洋岛国", "taipingyangdaoguo", "Pacific/Guadalcanal", "+11:00"),
        CityData("瓦努阿图维拉港", "Port Vila (Vanuatu)", "太平洋岛国", "taipingyangdaoguo", "Pacific/Efate", "+11:00"),
        CityData("萨摩亚阿皮亚", "Apia (Samoa)", "太平洋岛国", "taipingyangdaoguo", "Pacific/Apia", "+13:00")
    )

    /**
     * 生成500个热门城市的精准世界时钟数据
     */
    fun generateAccurate500WorldClocks(): List<WorldClockEntity> {
        return HOT_CITIES.map { cityData ->
            WorldClockEntity(
                cityName = cityData.cityName,
                cityEnglishName = cityData.cityEnglishName,
                countryName = cityData.countryName,
                countryPinyin = cityData.countryPinyin,
                zoneId = cityData.zoneId,
                timeOffset = cityData.timeOffset,
                currentTimeMills = 0,
                dayStatus = 0,
                selectedTime = -1
            )
        }.sortedWith(compareBy(Collator.getInstance(Locale.CHINA)) { it.cityName })
    }
}